# Generated by Django 5.2.5 on 2025-08-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_response_feedback_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('general', 'General Feedback'), ('issue', 'Issue Report'), ('task', 'Task Related'), ('training', 'Training Related'), ('survey', 'Survey Response'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
