# Generated by Django 5.2.5 on 2025-08-16 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_options_feedback_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Volunteer Feedback', 'verbose_name_plural': 'Volunteer Feedback'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Date when feedback was marked as resolved.', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(default=False, help_text="If checked, sender's identity will be hidden from recipients."),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, help_text='Coordinator/Admin reply to the volunteer', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_received', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
    ]
