# Generated by Django 5.2.5 on 2025-08-17 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_options_feedback_resolved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, help_text='If reassigned, this staff member will handle the feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reassigned', to=settings.AUTH_USER_MODEL, verbose_name='Reassigned To'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='survey_sent',
            field=models.BooleanField(default=False, help_text='Indicates if a follow-up survey was sent for this feedback.'),
        ),
    ]
