# Generated by Django 5.2.5 on 2025-08-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_surveyresponse_assigned_by_surveyresponse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='0 = not yet rated; 1–5 = actual rating', verbose_name='Overall rating (1–5)'),
        ),
    ]
