# Generated by Django 5.2.5 on 2025-08-17 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_surveyresponse_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Coordinator/Admin who assigned the survey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='q1',
            field=models.TextField(blank=True, null=True, verbose_name='What did you enjoy most about the program?'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='q2',
            field=models.TextField(blank=True, null=True, verbose_name='What could we improve?'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Optional rating: 1–5 = actual rating', null=True, verbose_name='Overall rating (1–5)'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='General Survey', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Users who should complete this survey', related_name='assigned_surveys', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.survey'),
        ),
    ]
