# Generated by Django 5.2.5 on 2025-08-20 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_alter_feedback_options_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='assigned_users',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='feedbackresponse',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reassigned_to',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='survey_sent',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='responded_by',
        ),
        migrations.AddField(
            model_name='feedback',
            name='anonymous_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='anonymous_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'General Feedback'), ('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('issue_report', 'Issue Report')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='Untitled Feedback', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15),
        ),
        migrations.CreateModel(
            name='FeedbackAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_feedback', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.feedbackcategory'),
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('feedback', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
