# Generated by Django 5.2.4 on 2025-08-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Volunteer', 'verbose_name_plural': 'Volunteers'},
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Admin', 'Admin'), ('Coordinator', 'Coordinator')], default='Volunteer', max_length=50),
        ),
    ]
