# Generated by Django 5.2.4 on 2025-08-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_volunteer_options_alter_volunteer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter phone number in international format e.g. +254712345678', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Admin', 'Admin'), ('Coordinator', 'Coordinator')], default='Volunteer', help_text='Select the role for this user', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(blank=True, help_text='List skills separated by commas', null=True),
        ),
    ]
