# Generated by Django 5.2.4 on 2025-08-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_volunteer_phone_alter_volunteer_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, help_text='Enter your address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='bio',
            field=models.TextField(blank=True, help_text='Write a short bio about yourself', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter your date of birth', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_pics/'),
        ),
    ]
