# Generated by Django 5.2.4 on 2025-08-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('task', 'Task'), ('training', 'Training'), ('recognition', 'Recognition'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
