# Generated by Django 5.2.5 on 2025-08-20 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.DurationField(help_text='Expected duration to complete the course')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Course',
                'verbose_name_plural': 'Training Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='assigned', max_length=20)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'Training Assignment',
                'verbose_name_plural': 'Training Assignments',
                'ordering': ['-assigned_date'],
                'unique_together': {('volunteer', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('issued_date', models.DateTimeField()),
                ('file', models.FileField(blank=True, help_text='Upload PDF certificate file', null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='training.trainingassignment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'Training Module',
                'verbose_name_plural': 'Training Modules',
                'ordering': ['order', 'course'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent', models.DurationField(blank=True, help_text='Time spent on this module', null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='training.trainingassignment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingmodule')),
            ],
            options={
                'verbose_name': 'Training Progress',
                'verbose_name_plural': 'Training Progress',
                'ordering': ['assignment', 'module'],
                'unique_together': {('assignment', 'module')},
            },
        ),
    ]
