# Generated by Django 5.2.5 on 2025-08-20 07:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='trainingassignment',
            options={'ordering': ['-assigned_date'], 'verbose_name': 'Training Assignment', 'verbose_name_plural': 'Training Assignments'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Training Course', 'verbose_name_plural': 'Training Courses'},
        ),
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={'ordering': ['order', 'course'], 'verbose_name': 'Training Module', 'verbose_name_plural': 'Training Modules'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogress',
            options={'ordering': ['assignment', 'module'], 'verbose_name': 'Training Progress', 'verbose_name_plural': 'Training Progress'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='time_spent',
            field=models.DurationField(blank=True, help_text='Time spent on this module', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='training.trainingassignment'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF certificate file', null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterUniqueTogether(
            name='trainingmodule',
            unique_together={('course', 'order')},
        ),
    ]
