# Generated by Django 5.2.4 on 2025-08-07 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='tier',
        ),
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingprogress',
            options={'ordering': ['-completed_at']},
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='role',
        ),
        migrations.RemoveField(
            model_name='trainingprogress',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='content',
            field=models.TextField(blank=True, help_text="If content_type is 'text' paste text here. For video/pdf/link, put URL or storage path."),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('pdf', 'PDF'), ('link', 'External Link')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.trainingmodule'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TrainingTier',
        ),
    ]
