# Generated by Django 5.2.4 on 2025-08-08 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_trainingmodule_tier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
