# Generated by Django 5.2.5 on 2025-08-15 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingmodule_assigned_to_trainingmodule_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
